-- CREAR ESQUEMA
CREATE TABLESPACE "GENERAL_DAT"
	LOGGING
	DATAFILE 'C:\app\edeldiego\oradata\orcl\CPPC_DAT.DBF' SIZE 512M
	EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "GENERAL_LOB"
	LOGGING
	DATAFILE 'C:\app\edeldiego\oradata\orcl\CPPC_LOB.DBF' SIZE 512M
	EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "GENERAL_IDX"
	LOGGING
	DATAFILE 'C:\app\edeldiego\oradata\orcl\CPPC_IDX.DBF' SIZE 512M
	EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


-- CREAR USUARIO
CREATE USER general PROFILE DEFAULT IDENTIFIED BY "general"
DEFAULT TABLESPACE GENERAL_DAT TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;

-- PERMISOS AL USUARIO
GRANT CONNECT TO general;
GRANT RESOURCE TO general;

-- PERMISOS DE OPERACION EN EL NUEVO ESQUEMA
GRANT CREATE MATERIALIZED VIEW TO general;
GRANT CREATE SYNONYM TO general;
GRANT DEBUG CONNECT SESSION TO general;
GRANT DROP PUBLIC SYNONYM TO general;
GRANT ALTER SESSION TO general;
GRANT CREATE TRIGGER TO general;
GRANT CREATE TYPE TO general;
GRANT CREATE ROLE TO general;
GRANT CREATE SEQUENCE TO general;
GRANT CREATE TABLE TO general;
GRANT CREATE VIEW TO general;
GRANT CREATE JOB TO general;
GRANT CREATE PROCEDURE TO general;
GRANT CREATE PUBLIC SYNONYM TO general;
GRANT CREATE ANY SYNONYM TO general;
GRANT CREATE SESSION TO general;
COMMIT;
