-- CREAR ESQUEMA
CREATE TABLESPACE "GENERAL_DAT"
	LOGGING
	DATAFILE 'C:\app\edeldiego\oradata\orcl\CPPC_DAT.DBF' SIZE 512M
	EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "GENERAL_LOB"
	LOGGING
	DATAFILE 'C:\app\edeldiego\oradata\orcl\CPPC_LOB.DBF' SIZE 512M
	EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE "GENERAL_IDX"
	LOGGING
	DATAFILE 'C:\app\edeldiego\oradata\orcl\CPPC_IDX.DBF' SIZE 512M
	EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


-- CREAR USUARIO
CREATE USER general PROFILE DEFAULT IDENTIFIED BY "general"
DEFAULT TABLESPACE GENERAL_DAT TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;

-- PERMISOS AL USUARIO
GRANT ALL PRIVILEGES TO general;
